version: '3.8'


services:
  core-service:
    image: lucassuntech/core-service:latest
    container_name: core_service
    ports:
      - "3334:3334"
    restart: always
  database:
    image: postgres:17.2
    container_name: local_db
    restart: always
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: core_service_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: