name: Deploy Staging

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

      # 2) Login no Docker Hub
      - name: Login no Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # 3) Build e push da imagem Docker
      - name: Build e Push da imagem
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/core-service:staging .
          docker push ${{ secrets.DOCKER_USERNAME }}/core-service:staging

      # 4) Deploy via SSH (Homolog)
      - name: Deploy no Staging (VPS)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Parar e remover container antigo
            if [ "$(docker ps -q -f name=core_service_staging)" ]; then
              docker stop core_service_staging
              docker rm core_service_staging
            fi

            # Puxar a imagem de staging
            docker pull ${{ secrets.DOCKER_USERNAME }}/core-service:staging

            # Rodar migrations dentro de um container transitório
            # Substitua "projects_default" pela rede do seu Docker (caso use Compose, verifique o nome da rede).
            docker run --rm \
              --network=projects_default \
              -e DATABASE_URL="${DATABASE_URL_HOMOLOG}" \
              ${{ secrets.DOCKER_USERNAME }}/core-service:staging \
              npx prisma migrate deploy

            # Subir o container com a imagem de staging
            docker run -d \
              --name core_service_staging \
              --network=projects_default \
              -e DATABASE_URL="${DATABASE_URL_HOMOLOG}" \
              -p 3335:3334 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/core-service:staging
        env:
          DATABASE_URL_HOMOLOG: ${{ secrets.DATABASE_URL_HOMOLOG }}
