name: Deploy Core-Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Exibir Variáveis de Ambiente (Debug)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "🔍 Verificando credenciais do Docker..."
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_ACCESS_TOKEN length: ${#DOCKER_ACCESS_TOKEN}"

      - name: Verificar se as variáveis estão vazias
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          if [[ -z "$DOCKER_USERNAME" || -z "$DOCKER_ACCESS_TOKEN" ]]; then
            echo "❌ Erro: DOCKER_USERNAME ou DOCKER_ACCESS_TOKEN não estão definidos!"
            exit 1
          else
            echo "✅ Variáveis carregadas corretamente!"
          fi

      - name: Logar no Docker Hub usando Access Token
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Construir e empurrar imagem para Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/core-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/core-service:latest

      - name: Deploy na VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/core-service:latest

            # Verifica se o container já existe antes de parar/remover
            if [ "$(docker ps -q -f name=core_service)" ]; then
              echo "🛑 Parando container antigo..."
              docker stop core_service
              docker rm core_service
            else
              echo "⚠️ Nenhum container antigo encontrado, pulando parada/remoção."
            fi

            echo "🚀 Iniciando novo container..."
            docker run -d --name core_service -p 3334:3334 --restart always ${{ secrets.DOCKER_USERNAME }}/core-service:latest
